name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.0, 5.0, 6.0]
    steps:
      -
        uses: actions/checkout@v2
        name: Checkout code
      -
        name: Build
        run: make build VERSION=${{ matrix.version }} DIST=fedora
      -
        name: Test
        run: make test VERSION=${{ matrix.version }} DIST=fedora
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.0, 5.0, 6.0]
    steps:
      -
        uses: actions/checkout@v2
        name: Checkout code
      -
        name: Build
        run: make build VERSION=${{ matrix.version }} DIST=fedora
      -
        name: Test
        run: make test VERSION=${{ matrix.version }} DIST=fedora
